import Head from "next/head";
import Image from "next/image";
import styles from "@scss/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favis/white/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favis/white/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favis/white/favicon-16x16.png"
        />
        <link rel="manifest" href="/favis/white/site.webmanifest" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>Welcome to {"Valento's"}</h3>

        <hr />
        <p className={styles.description}>Here we go...</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Post &rarr;</h2>
            <p>Soon to find out what about it...</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made by
            <Image src="/my_signature.svg" alt="My Logo" width={32} height={32} />
        </p>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
